### ISSUE TITLE
v1.3版本编译报错，二进制不兼容

### ISSUE THREAD

**Issue by hezhaoye** [Lax/traffic-accounting-nginx-module#33]
我使用的是nginx-1.10.2版本，在configurate的时候会报错：
traffic-accounting-nginx-module-1.3/src/ngxta_http_statuses.c:30:5: error: ‘NGX_HTTP_PERMANENT_REDIRECT’ undeclared here (not in a function)
traffic-accounting-nginx-module-1.3/src/ngxta_http_statuses.c:45:5: error: ‘NGX_HTTP_TOO_MANY_REQUESTS’ undeclared here (not in a function)
traffic-accounting-nginx-module-1.3/src/ngxta_http_statuses.c:58:5: error: ‘NGX_HTTP_VERSION_NOT_SUPPORTED’ undeclared here (not in a function)
去掉之后，configuratite正常了，编译后生成的so文件，拷贝到同样的系统，会报错：
module "/data/services/nginx-1.10.2.3/modules/ngx_http_accounting_module.so" is not binary compatible in /data/services/nginx-1.10.2.3/conf/nginx.conf:18
加入的内容是：load_module modules/ngx_http_accounting_module.so;，
请问，这是什么问题呢

**Comment by Lax** [comment]
please use v1.1
