### ISSUE TITLE
issue with dynamic building: "no suitable image found"

### ISSUE THREAD

**Issue by gWOLF3** [Lax/traffic-accounting-nginx-module#46]
What happened? 

followed instructions in readme - i included `load_module modules/ngx_http_accounting_module.so;` at the top level of my nginx.conf file, and added the downloaded .so file from releases in my /modules folder. 

However, I run into an error "no suitable image found". Any ideas? 

ENV: Im on a macbook, installed nginx with homebrew

Error: 
```
nginx: [emerg] dlopen() "/usr/local/Cellar/nginx/1.17.8/modules/ngx_http_accounting_module.so" failed (dlopen(/usr/local/Cellar/nginx/1.17.8/modules/ngx_http_accounting_module.so, 10): no suitable image found.  Did find:
	/usr/local/Cellar/nginx/1.17.8/modules/ngx_http_accounting_module.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/usr/local/Cellar/nginx/1.17.8/modules/ngx_http_accounting_module.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00) in /usr/local/etc/nginx/nginx.conf:1
```

**Comment by gWOLF3** [comment]
actually, I'm getting this issue on every release.

**Comment by Lax** [comment]
It seems you're running nginx on macOS, you have to build it on macOS (the binary in downloads page was build on Linux)
