### ISSUE TITLE
Keep getting the same error after following the installation steps.

### ISSUE THREAD

**Issue by Mikmist** [Lax/traffic-accounting-nginx-module#47]
Am still a bit of a noob at using modules in nginx so it might be something stupid that I just don't know about. 

`nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_accounting_module.so" failed (/etc/nginx/modules/ngx_http_accounting_module.so: undefined symbol: ngx_stream_get_variable_index) in /etc/nginx/nginx.conf:1`

**Comment by Lax** [comment]
Are you using a prebuild version or building it yourself?

**Comment by Mikmist** [comment]
Building myself.
